#database dev mode
spring:
  #get sql driver
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
  #sql connection info
    username: root
    password: 615615

  #simplify database connection and operation process
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #show sql log in console

logging:
  level:
    root: info
    com.zyu: debug
  file: log/blog-dev.log



